wger/exercises/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required

from wger.exercises.views import (
    exercises,
    comments,
    categories,
    muscles,
    images,
    equipment
)



# sub patterns for muscles
patterns_muscle = [
    url(r'^overview/$',
        muscles.MuscleListView.as_view(),
        name='overview'),
    url(r'^admin-overview/$',
        muscles.MuscleAdminListView.as_view(),
        name='admin-list'),
    url(r'^add/$',
        muscles.MuscleAddView.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/edit/$',
        muscles.MuscleUpdateView.as_view(),
        name='edit'),
    url(r'^(?P<pk>\d+)/delete/$',
        muscles.MuscleDeleteView.as_view(),
        name='delete'),
]

# sub patterns for exercise images
patterns_images = [
    url(r'^(?P<exercise_pk>\d+)/image/add$',
        images.ExerciseImageAddView.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/edit$',
        images.ExerciseImageEditView.as_view(),
        name='edit'),
    url(r'^(?P<exercise_pk>\d+)/image/(?P<pk>\d+)/delete$',
        images.ExerciseImageDeleteView.as_view(),
        name='delete'),
    url(r'^(?P<pk>\d+)/accept/$',
        images.accept,
        name='accept'),
    url(r'^(?P<pk>\d+)/decline/$',
        images.decline,
        name='decline'),
]

# sub patterns for exercise comments
patterns_comment = [
    url(r'^(?P<exercise_pk>\d+)/comment/add/$',
        comments.ExerciseCommentAddView.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/edit/$',
        comments.ExerciseCommentEditView.as_view(),
        name='edit'),
    url(r'^(?P<id>\d+)/delete/$',
        comments.delete,
        name='delete'),
]

# sub patterns for categories
patterns_category = [
    url(r'^list$',
        categories.ExerciseCategoryListView.as_view(),
        name='list'),
    url(r'^(?P<pk>\d+)/edit/$',
        categories.ExerciseCategoryUpdateView.as_view(),
        name='edit'),
    url(r'^add/$',
        categories.ExerciseCategoryAddView.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/delete/$',
        categories.ExerciseCategoryDeleteView.as_view(),
        name='delete'),
]

# sub patterns for equipment
patterns_equipment = [
    url(r'^list$',
        equipment.EquipmentListView.as_view(),
        name='list'),
    url(r'^add$',
        equipment.EquipmentAddView.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/edit$',
        equipment.EquipmentEditView.as_view(),
        name='edit'),
    url(r'^(?P<pk>\d+)/delete$',
        equipment.EquipmentDeleteView.as_view(),
        name='delete'),
    url(r'^overview$',
        equipment.EquipmentOverviewView.as_view(),
        name='overview'),
]


# sub patterns for exercises
patterns_exercise = [
    url(r'^overview/$',
        exercises.ExerciseListView.as_view(),
        name='overview'),
    url(r'^(?P<id>\d+)/view/$',
        exercises.view,
        name='view'),
    url(r'^(?P<id>\d+)/view/(?P<slug>[-\w]*)/?$',
        exercises.view,
        name='view'),
    url(r'^add/$',
        login_required(exercises.ExerciseAddView.as_view()),
        name='add'),
    url(r'^(?P<pk>\d+)/edit/$',
        exercises.ExerciseUpdateView.as_view(),
        name='edit'),
    url(r'^(?P<pk>\d+)/correct$',
        exercises.ExerciseCorrectView.as_view(),
        name='correct'),
    url(r'^(?P<pk>\d+)/delete/$',
        exercises.ExerciseDeleteView.as_view(),
        name='delete'),
    url(r'^pending/$',
        exercises.PendingExerciseListView.as_view(),
        name='pending'),
    url(r'^(?P<pk>\d+)/accept/$',
        exercises.accept,
        name='accept'),
    url(r'^(?P<pk>\d+)/decline/$',
        exercises.decline,
        name='decline'),
]


urlpatterns = [
   url(r'^muscle/', include(patterns_muscle, namespace="muscle")),
   url(r'^image/', include(patterns_images, namespace="image")),
   url(r'^comment/', include(patterns_comment, namespace="comment")),
   url(r'^category/', include(patterns_category, namespace="category")),
   url(r'^equipment/', include(patterns_equipment, namespace="equipment")),
   url(r'^', include(patterns_exercise, namespace="exercise")),
]

wger/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

from tastypie.api import Api
from rest_framework import routers

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from wger.nutrition.sitemap import NutritionSitemap
from wger.exercises.sitemap import ExercisesSitemap

from wger.utils.generic_views import TextTemplateView
from wger.utils.generic_views import WebappManifestView

from wger.exercises.api import resources as exercises_api
from wger.nutrition.api import resources as nutrition_api
from wger.manager.api import resources as manager_api
from wger.core.api import resources as core_api
from wger.weight.api import resources as weight_api

from wger.manager.api import views as manager_api_views
from wger.core.api import views as core_api_views
from wger.exercises.api import views as exercises_api_views
from wger.nutrition.api import views as nutrition_api_views
from wger.weight.api import views as weight_api_views

#
# REST API
#

### /api/v1 - tastypie - deprecated
v1_api = Api(api_name='v1')

v1_api.register(exercises_api.ExerciseCategoryResource())
v1_api.register(exercises_api.ExerciseCommentResource())
v1_api.register(exercises_api.ExerciseImageResource())
v1_api.register(exercises_api.ExerciseResource())
v1_api.register(exercises_api.MuscleResource())
v1_api.register(exercises_api.EquipmentResource())

v1_api.register(nutrition_api.IngredientResource())
v1_api.register(nutrition_api.WeightUnitResource())
v1_api.register(nutrition_api.NutritionPlanResource())
v1_api.register(nutrition_api.MealResource())
v1_api.register(nutrition_api.MealItemResource())
v1_api.register(nutrition_api.IngredientToWeightUnit())

v1_api.register(manager_api.WorkoutResource())
v1_api.register(manager_api.ScheduleResource())
v1_api.register(manager_api.ScheduleStepResource())
v1_api.register(manager_api.DayResource())
v1_api.register(manager_api.SetResource())
v1_api.register(manager_api.SettingResource())
v1_api.register(manager_api.WorkoutLogResource())
v1_api.register(manager_api.WorkoutSessionResource())

v1_api.register(weight_api.WeightEntryResource())

v1_api.register(core_api.LanguageResource())
v1_api.register(core_api.DaysOfWeekResource())
v1_api.register(core_api.UserProfileResource())
v1_api.register(core_api.LicenseResource())

### /api/v2 - django rest framework
router = routers.DefaultRouter()

# Manager app
router.register(r'workout', manager_api_views.WorkoutViewSet, base_name='workout')
router.register(r'workoutsession', manager_api_views.WorkoutSessionViewSet, base_name='workoutsession')
router.register(r'schedulestep', manager_api_views.ScheduleStepViewSet, base_name='schedulestep')
router.register(r'schedule', manager_api_views.ScheduleViewSet, base_name='schedule')
router.register(r'day', manager_api_views.DayViewSet, base_name='day')
router.register(r'set', manager_api_views.SetViewSet, base_name='Set')
router.register(r'setting', manager_api_views.SettingViewSet, base_name='Setting')
router.register(r'workoutlog', manager_api_views.WorkoutLogViewSet, base_name='workoutlog')

# Core app
router.register(r'userprofile', core_api_views.UserProfileViewSet, base_name='userprofile')
router.register(r'language', core_api_views.LanguageViewSet, base_name='language')
router.register(r'daysofweek', core_api_views.DaysOfWeekViewSet, base_name='daysofweek')
router.register(r'license', core_api_views.LicenseViewSet, base_name='license')
router.register(r'setting-repetitionunit', core_api_views.RepetitionUnitViewSet, base_name='setting-repetition-unit')
router.register(r'setting-weightunit', core_api_views.WeightUnitViewSet, base_name='setting-weight-unit')

# Exercises app
router.register(r'exercise', exercises_api_views.ExerciseViewSet, base_name='exercise')
router.register(r'equipment', exercises_api_views.EquipmentViewSet, base_name='api')
router.register(r'exercisecategory', exercises_api_views.ExerciseCategoryViewSet, base_name='exercisecategory')
router.register(r'exerciseimage', exercises_api_views.ExerciseImageViewSet, base_name='exerciseimage')
router.register(r'exercisecomment', exercises_api_views.ExerciseCommentViewSet, base_name='exercisecomment')
router.register(r'muscle', exercises_api_views.MuscleViewSet, base_name='muscle')

# API Users
router.register(r'user', core_api_views.UserAPIView, base_name='user')

# Nutrition app
router.register(r'ingredient', nutrition_api_views.IngredientViewSet, base_name='api-ingredient')
router.register(r'weightunit', nutrition_api_views.WeightUnitViewSet, base_name='weightunit')
router.register(r'ingredientweightunit', nutrition_api_views.IngredientWeightUnitViewSet,
                base_name='ingredientweightunit')
router.register(r'nutritionplan', nutrition_api_views.NutritionPlanViewSet, base_name='nutritionplan')
router.register(r'meal', nutrition_api_views.MealViewSet, base_name='meal')
router.register(r'mealitem', nutrition_api_views.MealItemViewSet, base_name='mealitem')

# Weight app
router.register(r'weightentry', weight_api_views.WeightEntryViewSet, base_name='weightentry')

from django.contrib import admin
admin.autodiscover()

#
# Sitemaps
#
sitemaps = {'exercises': ExercisesSitemap,
            'nutrition': NutritionSitemap}

#
# The actual URLs
#
urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('wger.core.urls', namespace='core', app_name='core')),
    url(r'workout/', include('wger.manager.urls', namespace='manager')),
    url(r'exercise/', include('wger.exercises.urls', namespace='exercise')),
    url(r'weight/', include('wger.weight.urls', namespace='weight')),
    url(r'nutrition/', include('wger.nutrition.urls', namespace='nutrition')),
    url(r'software/', include('wger.software.urls', namespace='software', app_name='software')),
    url(r'config/', include('wger.config.urls', namespace='config', app_name='config')),
    url(r'gym/', include('wger.gym.urls', namespace='gym', app_name='gym')),
    url(r'email/', include('wger.email.urls', namespace='email')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='sitemap')
)

#
# URLs without language prefix
#
urlpatterns += [
    url(r'^robots\.txt$',
        TextTemplateView.as_view(template_name="robots.txt"),
        name='robots'),
    url(r'^manifest\.webapp$', WebappManifestView.as_view(template_name="manifest.webapp")),
    url(r'^amazon-manifest\.webapp$', WebappManifestView.as_view(template_name="amazon-manifest.webapp")),

    # API
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/exercise/search/$',
        exercises_api_views.search,
        name='exercise-search'),
    url(r'^api/v2/exercise/view/$',
        exercises_api_views.view_exercise,
        name='view_excercise'),
    url(r'^api/v2/ingredient/search/$',
        nutrition_api_views.search,
        name='ingredient-search'),
    url(r'^api/v2/', include(router.urls)),
]

#
# URL for user uploaded files, served like this during development only
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wger/utils/models.py
# -*- coding: utf-8 -*-

# This file is part of Workout Manager.
#
# Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

from django.db import models
from django.utils.translation import ugettext_lazy as _

from wger.core.models import License


'''
Abstract model classes
'''


class AbstractLicenseModel(models.Model):
    '''
    Abstract class that adds license information to a model
    '''

    class Meta:
        abstract = True

    license = models.ForeignKey(License,
                                verbose_name=_('License'),
                                default=2)
    '''The item's license'''

    license_author = models.CharField(verbose_name=_('Author'),
                                      max_length=50,
                                      blank=True,
                                      null=True,
                                      help_text=_('If you are not the author, enter the name or '
                                                  'source here. This is needed for some licenses '
                                                  'e.g. the CC-BY-SA.'))
    '''The author if it is not the uploader'''


class AbstractSubmissionModel(models.Model):
    '''
    Abstract class used for model for user submitted data.

    These models have to be approved first by an administrator before they are
    shows in the website. There is also a manager that can be used:
    utils.managers.SubmissionManager
    '''

    class Meta:
        abstract = True

    STATUS_PENDING = '1'
    STATUS_ACCEPTED = '2'
    STATUS_DECLINED = '3'

    STATUS = (
        (STATUS_PENDING, _('Pending')),
        (STATUS_ACCEPTED, _('Accepted')),
        (STATUS_DECLINED, _('Declined')),
    )

    status = models.CharField(max_length=2,
                              choices=STATUS,
                              default=STATUS_PENDING,
                              editable=False)
    '''Status of the submission, e.g. accepted or declined'''

wger/exercises/forms.py
# -*- coding: utf-8 -*-

# This file is part of Workout Manager.
#
# Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

from django import forms

from wger.exercises.models import ExerciseImage, ExerciseComment


class ExerciseImageForm(forms.ModelForm):
    class Meta:
        model = ExerciseImage
        fields = ('image',
                  'is_main',
                  'license',
                  'license_author')


class CommentForm(forms.ModelForm):
    class Meta:
        model = ExerciseComment
        exclude = ('exercise',)

wger/exercises/templates/exercise/view.html
{% extends "base.html" %}
{% load i18n staticfiles wger_extras thumbnail cache django_bootstrap_breadcrumbs %}


{#           #}
{# Opengraph #}
{#           #}
{% block opengraph %}
    {{ block.super }}
    <meta property="og:title" content="{{ exercise.name }}">
    <meta property="og:description" content="{{ exercise.description_clean }}">
{% endblock %}
{% block opengraphimages %}
    {% for image in exercise.exerciseimage_set.accepted %}
        <meta property="og:image" content="{{ image.image.url }}">
    {% empty %}
        <meta property="og:image" content="{{ image_absolute_path }}">
    {% endfor %}
{% endblock %}


{#             #}
{# Breadcrumbs #}
{#             #}
{% block breadcrumbs %}
    {{ block.super }}

    {% breadcrumb "Exercises" "exercise:exercise:overview" %}
    {% breadcrumb exercise exercise.get_absolute_url %}
{% endblock %}


{#       #}
{# Title #}
{#       #}
{% block title %}{{ exercise.name }}{% endblock %}


{#        #}
{# Header #}
{#        #}
{% block header %}
<script>
$(document).ready(function() {
    wgerDrawWeightLogChart({{json|safe}}, "{{svg_uuid}}");
});
</script>
{% endblock %}


{#         #}
{# Content #}
{#         #}
{% block content %}

{% if exercise.status == exercise.STATUS_PENDING %}
<div class="panel panel-default">
    <div class="panel-heading">{% trans "Exercise is pending review" %}</div>
    <div class="panel-body">
        <p>{% blocktrans %}This user submitted exercise is pending a decision to be
        included in the database.{% endblocktrans %}
        {% trans "Till then, it will not be shown in the overview or the search."  %}
        {% if perms.exercises.add_exercise %}{% trans "Please select one of the options below." %}{% endif %}
        </p>

        {% if perms.exercises.add_exercise %}
        <div class="btn-group btn-group-justified" role="group">

            <a href="{% url 'exercise:exercise:accept' exercise.id %}" class="btn btn-default">
                <span class="{% fa_class 'check' %}"></span>
                {% trans "Accept" %}
            </a>
            <a href="{% url 'exercise:exercise:decline' exercise.id %}" class="btn btn-default">
                <span class="{% fa_class 'times' %}"></span>
                {% trans "Decline" %}
            </a>
        </div>
        {% endif %} {# end check permissions #}
    </div>
</div>
{% endif %} {# end exercise is pending review #}



<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        <strong>{% trans "Category" %}:</strong>
    </div>
    <div class="col-xs-9">
        {% trans exercise.category.name %}
    </div>
</div>

{% if exercise.equipment.all %}
<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        <strong>{% trans "Equipment" %}:</strong>
    </div>
    <div class="col-xs-9">
        {% for equipment in exercise.equipment.all %}
            {% trans equipment.name %}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}


<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        <strong>{% trans "Description" %}:</strong>
    </div>
    <div class="col-xs-9">
        {{ exercise.description|safe }}
    </div>
</div>



{# Images #}
{% with images=exercise.exerciseimage_set.accepted %}
{% if images or perms.exercises.change_exerciseimage  %}
<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        {% if perms.exercises.change_exerciseimage %}
        <p>
            <a href="{% url 'exercise:image:add' exercise.id %}" class="btn btn-success btn-xs">
                {% trans "Add new image" %}
            </a>
        </p>
        {% endif %}
{#        <strong>{% trans "Images" %}:</strong>#}
    </div>
    <div class="col-xs-9">
        <div class="image-gallery">
        {% with other_images=images %}
        {% for image in other_images %}
            <div class="image-box">
                <div class="boxInner">
                    <img src="{{ image.image|thumbnail_url:'small' }}"
                         alt=""
                         class="gallery-image">

                    <div class="titleBox">
                        <a href="{{ image.image.url }}"
                           target="_blank"
                           class=" no-hover"
                           title="{% trans 'Download' %}">
                             <span class="{% fa_class 'download' %}"></span></a>
                        {% if perms.exercises.change_exerciseimage %}
                        |
                        <a href="{% url 'exercise:image:delete' exercise.pk image.pk %}"
                           class="wger-modal-dialog no-hover"
                           title="{% trans 'Delete' %}">
                             <span class="{% fa_class 'trash' %}"></span></a> |
                        <a href="{% url 'exercise:image:edit' image.pk %}"
                           class="no-hover"
                           title="{% trans 'Edit' %}">
                             <span class="{% fa_class 'pencil-square-o' %}"></span></a>
                        {% endif %}

                        <br>
                        {{image.get_license_display}}
                        {% if image.license_author %}
                             – {{image.license_author}}
                        {% endif %}

                    </div>
                </div>
            </div>
        {% endfor %}
        {% endwith %}
        </div>
    </div>
</div>
{% endif %}
{% endwith %}

{% if perms.exercises.change_exerciseimage %}
{% with images=exercise.exerciseimage_set.pending %}
{% if images %}
<h4>{% trans "Images pending review" %}</h4>
<div class="list-group">
    {% for image in images %}
        <div class="list-group-item">
            <div class="media">
                <div style="width:60px;height:60px;" class="pull-left">
                    <a href="{{image.image.url}}">
                        <img alt="{{ image.exercise.name }}"
                             class="media-object "
                             style="max-width:100%; max-height:100%;"
                             src="{{ image.image|thumbnail_url:'thumbnail' }}">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ image.image }}</h4>
                    <a href="{% url 'exercise:image:accept' image.pk %}" class="btn btn-default btn-sm">{% trans "Accept" %}</a>
                    <a href="{% url 'exercise:image:decline' image.pk %}" class="btn btn-default btn-sm">{% trans "Decline" %}</a>
                    <a href="{% url 'exercise:image:delete' exercise.pk image.pk %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                 </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endif %}  {# end check permission #}


{# Comments #}
{% with comments=exercise.exercisecomment_set.all %}
{% if comments or perms.exercises.change_exercisecomment %}
<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        <strong>{% trans "Comments for this exercise" %}:</strong>
    </div>
    <div class="col-xs-9">
        <ul>
        {% for comment in comments %}
            <li>
                {{ comment }}
                {% if perms.exercises.change_exercisecomment %}
                <span class="editoptions">
                    <a href="{% url 'exercise:comment:delete' comment.id %}"
                       title="{% trans 'Delete' %}">
                        <span class="{% fa_class 'trash' %}"></span></a>
                    <a href="{% url 'exercise:comment:edit' comment.id %}"
                       title="{% trans 'Edit' %}"
                       class="wger-modal-dialog">
                        <span class="{% fa_class 'pencil-square-o' %}"></span></a>
                </span>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endif %}
{% endwith %}

{% if perms.exercises.change_exercisecomment %}
<p>
    <a href="{% url 'exercise:comment:add' exercise.id %}" class="btn btn-success btn-xs wger-modal-dialog">
        {% trans "Add new comment" %}
    </a>
</p>
{% endif %}



{% cache cache_timeout exercise-detail-muscles exercise.id language.id %}
{% with muscles=exercise.muscles.all %}
{% with muscles_secondary=exercise.muscles_secondary.all %}

{% if muscles %}
<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        <strong>{% trans "Muscles" %}:</strong>
    </div>
    <div class="col-xs-9">
        <p>
            {% trans "The diagram shows the most used muscles on this exercise" %}
        </p>
        <div>
            <div style="width:1em;height:1em;background-color:#cc0000;float:left;margin-right:0.5em;"></div>
            {% trans "Main muscles" %}
        </div>

        <div>
            <div style="width:1em;height:1em;background-color:#f57900;float:left;margin-right:0.5em;"></div>
            {% trans "Secondary muscles" %}
        </div>
        <div class="row" style="margin-top:1em;">
            <div class="col-md-6 col-xs-6">
                <div id="muscle-front" class="muscle-background center-block" style="background-image: {% for background in muscle_backgrounds_front %}url({% static background %}){% if not forloop.last %},{% endif %}{% endfor %};">
                </div>
                <ul>
                    {% for muscle in muscles %}
                        {% if muscle.is_front %}
                            <li>{{muscle.name}}</li>
                        {% endif %}
                    {% endfor %}

                    {% for muscle in muscles_secondary %}
                        {% if muscle.is_front %}
                            <li>{{muscle.name}}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6 col-xs-6">
                <div id="muscle-back" class="muscle-background center-block" style="background-image: {% for background in muscle_backgrounds_back %}url({% static background %}){% if not forloop.last %},{% endif %}{% endfor %};">
                </div>
                <ul>
                    {% for muscle in muscles %}
                        {% if not muscle.is_front %}
                            <li>{{muscle.name}}</li>
                        {% endif %}
                    {% endfor %}

                    {% for muscle in muscles_secondary %}
                        {% if not muscle.is_front %}
                            <li>{{muscle.name}}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endwith %}
{% endwith %} {# end musclelist #}
{% endcache %}

{% if logs %}
<div class="row" style="margin-top:1em;">
    <div class="col-xs-3">
        <strong>{% trans "Weight log" %}:</strong>
    </div>
    <div class="col-xs-9">
        {% render_weight_log logs svg_uuid user %}
    </div>
</div>


<script>

</script>
{% endif %}

{% endblock %}


{#          #}
{# Side bar #}
{#          #}
{% block sidebar %}
{% if user.is_authenticated and not user.userprofile.is_temporary and not perms.exercises %}
<h4>{% trans "Options" %}</h4>
<p>
    <a href="{% url 'exercise:exercise:correct' exercise.id %}" {% auto_link_css flavour %}>
        <span class="{% fa_class 'pencil-square-o' %}"></span>
        {% trans "Submit a correction" %}
    </a>
</p>
{% endif %}

{% license_sidebar exercise.license exercise.license_author %}
{% endblock %}



{#         #}
{# Options #}
{#         #}
{% block options %}
{% if perms.exercises.change_exercise %}
<div class="btn-group">
    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="{% fa_class 'cog' %}"></span>
        {% trans "Options" %}
    </button>
    <ul class="dropdown-menu">
        <li>
            <a href="{% url 'exercise:exercise:edit' exercise.id %}">
                <span class="{% fa_class 'pencil-square-o' %}"></span>
                {% trans "Edit" %}
            </a>
        </li>
        <li>
            <a href="{% url 'exercise:exercise:delete' exercise.id %}" class="wger-modal-dialog" %}>
                <span class="{% fa_class 'trash' %}"></span>
                {% trans "Delete" %}
            </a>
        </li>
    </ul>
</div>
{% endif %}
{% endblock %}